# Generated by Django 4.2.3 on 2023-07-07 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='upload',
            old_name='uploaded_by',
            new_name='uploaded_by_id',
        ),
        migrations.AddField(
            model_name='upload',
            name='uploaded_by_email',
            field=models.EmailField(default='DUMMY_EMAIL', max_length=254),
        ),
    ]
