# Generated by Django 4.2.3 on 2023-07-07 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usermodel',
            old_name='user_id',
            new_name='id',
        ),
    ]
