# Generated by Django 4.2.3 on 2023-07-05 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_id_user_email_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.TextField(blank=True, max_length=256),
        ),
    ]
