# Generated by Django 4.2.3 on 2023-07-07 18:30

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_user_id_usermodel_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='access_shared_ids',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True), blank=True, default=[], size=None),
        ),
    ]
