# Generated by Django 4.2.3 on 2023-07-07 18:40

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_usermodel_access_shared_ids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='access_shared_ids',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True), size=20),
        ),
    ]
